[package]
name = "quotient"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.9.0"
clap = { version = "4.5.37", features = ["derive"] }
codespan-reporting = "0.12.0"
ordered-float = "5.0.0"
phf = { version = "0.11.3", features = ["macros"] }
