[package]
name = "quotient"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
miette = { version = "=4.7.0", features = ["fancy"] }
structs2enum_macro = { path = "./structs2enum_macro" }
thiserror = "2.0.12"
